name: Tests

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Execute tests
              run: docker compose app server npm run test
            # - name: Install modules
            #   run: npm install

            # - name: Run tests
            #   run: npm run test
